### ISSUE TITLE
I love bezels!

### ISSUE THREAD

**Issue by ratmandom** [cosmo0/arcade-manager#1]
hello could you tell me more about this, would this work for all retroarch bezels IE the wii u/ps vita and so on? that would be amazing my friend I have all ways wanted that tool. and I think that the retroarch project will catch on to more settings, some time but not today. - I think quote me if I am wrong mate.

bezels are amazing I want them for every system with the black boarders, I was even thinking how hard would it be to code them into separate/single emulators with the old aspect ratio... any way that would be a perfect world to me...

I am new to this and I have started learning coding-not long a go after a while of playing about with games.

**Comment by ratmandom** [comment]
I would help supporting a good tool like this $

**Comment by cosmo0** [comment]
Hello

Thank you for the kind words.

I already have a repository for bezels for Retropie : https://github.com/cosmo0/retropie-overlays . They are a copy-and-paste installation, but they are pre-configured for Retropie.  
It's not very hard to make them fit your system, you just have to find where the configs are located (that's the hard part) then edit the files to point to the right folders (a search-and-replace will suffice).  
I considered making them cross-platform but each system has their own files layout, I didn't want to bother.

I'm closing this issue since it's not related to the arcade manager.
