### ISSUE TITLE
Rom manager deleting bios files

### ISSUE THREAD

**Issue by halpz** [cosmo0/arcade-manager#5]
when I trim down my rom list using one of the built in CSV's such as best games etc, it deletes vital BIOS files for certain games to work.

it would be good if you could whitelist MAME and FBA bios zips from being deleted with these scripts

**Comment by cosmo0** [comment]
This will be included in the next version (yeah it took me 4 years lol)

**Comment by RGS-MBU** [comment]
Ok this is funny, while I was using your tool. BTW I love it! I trim down a full set from a CSV But when I compared my list to the output there where always more files in the output! why.. because they are BIOS haha. So I use a non-merged romset with bios incl. in the parent and clone roms. But now I see this was a issue, I think they where using a merged or split set. So you won't need the bios files for non-merged.

Thnx!
