### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by djibux** [cosmo0/arcade-manager#8]
Hello,
I like your work and would like to send in a donation.  What's the best way to do that?

**Comment by GiulioCentorame** [comment]
I second this, it's a great tool and definitely the most user-friendly utility out there!

**Comment by halpz** [comment]
Please keep working on this! update for FBNeo etc!

**Comment by halpz** [comment]
Also are overlays meant to be greyed out on the Windows version?

**Comment by cosmo0** [comment]
Hello and thanks for your interest (and sorry for the delay).

I won't take donations because I don't want to have a sense of obligation, but I appreciate the offer (and the kind comments) :)

@halpz: the overlays cannot be installed automatically if you're using RetroArch on Windows because I don't know where it's installed (and I don't even know where to copy the files), whereas Retropie and Recalbox have a fixed and predictable folde folder structure.
